#if !canImport(ObjectiveC)
import XCTest

extension JSONCodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONCodableTests = [
        ("testCodableFormat1", testCodableFormat1),
        ("testCodableFormatCustom", testCodableFormatCustom),
        ("testJSONCodable1", testJSONCodable1),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONCodableTests.__allTests__JSONCodableTests),
    ]
}
#endif
